Repository openebs/cstor-operators, pull requests merged in 2020-05, with the labels that each got.

#47 feat(webhook): add volume specific webhook validations
  pkg/webhook/configuration.go
  pkg/webhook/cvc.go
  pkg/webhook/cvc_test.go
  pkg/webhook/webhook.go
Labels: admission-webhook, area: cvc-operator

#54 add travis sanity check
  .travis.yml
  ci/artifacts/busybox-csi-cstor-sparse.yaml
  ci/artifacts/csi-operator-ubuntu-18.04.yaml
  ci/artifacts/csi-storageclass.yaml
  ci/artifacts/cspc-template.yaml
  ci/sanity/install.sh
  ci/sanity/sanity.sh
Labels: needs-review

#49 chore(refactor) : add fake controller testing for cspc-operator
  pkg/controllers/cspc-controller/handler_test.go
  pkg/controllers/cspc-controller/sync.go
  pkg/controllers/testutil/test_utils.go
  pkg/cspc/algorithm/select_node.go
  pkg/pool/operations/create.go
Labels: area: cspc-operator, needs-review

#46 feat(webhook): add cspc expansion validations
  pkg/webhook/cspc.go
  pkg/webhook/cspc_operations.go
  pkg/webhook/cspc_operations_test.go
  pkg/webhook/cspc_test.go
Labels: admission-webhook

#59 chore(push_script): refactor makefile and push scirpt
  Makefile
  build/cspc-operator/Dockerfile
  build/cstor-webhook/Dockerfile
  build/cvc-operator/Dockerfile
  build/cvc-operator/Dockerfile.arm64
  build/pool-manager/Dockerfile
  build/push
  build/volume-manager/Dockerfile
  build/volume-manager/Dockerfile.arm64
Labels: needs-review

#52 feat(policy): reconcile volume policy per volume bases
  Makefile
  go.mod
  pkg/controllers/cstorvolumeconfig/controller.go
  pkg/controllers/cstorvolumeconfig/deployment.go
  pkg/controllers/cstorvolumeconfig/policy.go
  pkg/cspc/algorithm/select_node.go
  pkg/hash/hash.go
  pkg/util/hash/hash.go
  pkg/util/hash/hash_test.go
  pkg/volumereplica/volumereplica.go
  pkg/webhook/cspc.go
  pkg/webhook/cvc.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: area: cvc-operator, area: volume-policy, documentation, needs-review, pr/upgrade-automated

#66 chore(ci): fast fail travis script in case of error
  .travis.yml
  ci/sanity/install.sh
  ci/sanity/sanity.sh
Labels: area: ci, needs-review

#60 feat(upgrade): add upgrade framework in controllers
  pkg/controllers/cspc-controller/handler.go
  pkg/controllers/cspc-controller/sync.go
  pkg/controllers/cspi-controller/handler.go
  pkg/controllers/cspi-controller/volumereplica/handler.go
  pkg/controllers/cstorvolumeconfig/controller.go
  pkg/controllers/volume-mgmt/handler.go
Labels: needs-review

#69 cherry-pick(log): add more information in error event (#68)
  pkg/controllers/cstorvolumeconfig/volume_operations.go
Labels: area: cvc-operator

#67 add repo documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/developer-guide/devel.md
  docs/developer-guide/start.md
  docs/quick.md
  docs/tutorial/cspc/mirror/mirror.md
  docs/tutorial/cspc/stripe/stripe.md
  docs/tutorial/intro.md
Labels: needs-review

#73 chore(docs): add changelog for v1.10.0 release
  CHANGELOG.md
Labels: pr/hold-merge

#77 fix(cspi): import pool without cachefile
  ci/sanity/sanity.sh
  go.mod
  go.sum
  pkg/pool/operations/import.go
  vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorpoolcluster.go
  vendor/github.com/openebs/api/pkg/apis/openebs.io/v1alpha1/blockdeviceclaimbuilder.go
  vendor/github.com/openebs/api/pkg/apis/types/types.go
  vendor/modules.txt
Labels: pr/hold-merge

#78 cherry-pick(cspi): import pool without cachefile
  ci/sanity/sanity.sh
  go.mod
  go.sum
  pkg/pool/operations/import.go
  vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorpoolcluster.go
  vendor/github.com/openebs/api/pkg/apis/openebs.io/v1alpha1/blockdeviceclaimbuilder.go
  vendor/github.com/openebs/api/pkg/apis/types/types.go
  vendor/modules.txt
Labels: pr/hold-merge

#82 fix(webhook): fix blockdevice replacement validation
  pkg/webhook/cspc_operations.go
  pkg/webhook/cspc_test.go
Labels: admission-webhook, needs-review
