Repository openebs/cstor-operators, pull requests merged in 2020-07, with the labels that each got.

#110 refact(webhook): make webhook config failure policy configurable
  deploy/cstor-operator.yaml
  pkg/webhook/configuration.go
Labels: admission-webhook, needs-review, pr/release-note

#93 chore(cvc): add cvc-controller fake client mock tests
  pkg/controllers/cstorvolumeconfig/controller_base.go
  pkg/controllers/cstorvolumeconfig/controller_test.go
Labels: needs-review

#117 test(unit test): add test cases for cstor pool provisioning
  pkg/controllers/cspi-controller/handler_test.go
  pkg/webhook/cspc.go
  pkg/webhook/cspc_test.go
Labels: needs-review

#122 fix(cstor-webhook): fixes pool scaledown bug
  pkg/webhook/cspc.go
Labels: admission-webhook, bug

#132 chore(docs): add cspc tunables docs
  docs/tutorial/cspc/tuning/tune.md
  docs/tutorial/intro.md
Labels: documentation, needs-review

#131 chore(docs): add cStor pool resource organization docs
  README.md
  docs/developer-guide/cstor-pool.md
Labels: documentation, needs-review

#135 fix(cstor-webhook): allow scale down of pools when node doesn't exist in cluster
  pkg/webhook/cspc_operations.go
  pkg/webhook/cspc_test.go
Labels: admission-webhook, bug

#137 chore(docs): add troubleshoot steps to bring cStor pools online after performing node replacement
  docs/troubleshooting/migrate_pool_by_migrating_disks.md
  docs/tutorial/intro.md
  docs/tutorial/volumes/migration.md
Labels: documentation, needs-review

#136 chore(docs): add volume policy docs with example configurations
  docs/tutorial/volumes/policy.md
Labels: documentation, needs-review

#139 docs(bad_disk): add troubleshooting document to recover stuck pool pod
  README.md
  docs/troubleshooting/pool_operations_hung.md
  docs/troubleshooting/troubleshooting.md
  docs/tutorial/intro.md
Labels: needs-review

#138 chore(docs): add troubleshooting steps to migrate cStor volume from lost pool to new pool
  docs/troubleshooting/migrate_cstor_volume.md
  docs/troubleshooting/pool_operations_hung.md
  docs/troubleshooting/troubleshooting.md
Labels: documentation, needs-review

#142 chore(docs): add prerequisite to install CStor-CSI on rancher based cluster
  docs/quick.md
  docs/troubleshooting/migrate_cstor_volume.md
  docs/troubleshooting/rancher_prerequisite.md
  docs/troubleshooting/troubleshooting.md
Labels: documentation
