Repository openebs/cstor-operators, pull requests merged in 2020-08, with the labels that each got.

#140 chore(yaml): add generic CSI operator yaml with root mount
  .travis.yml
  ci/artifacts/busybox-csi-cstor-sparse.yaml
  ci/sanity/install.sh
  ci/sanity/sanity.sh
  deploy/csi-operator-ubuntu-18.04.yaml
  deploy/csi-operator.yaml
  deploy/snapshot_class.yaml
  docs/quick.md
Labels: needs-review

#141 fix(status): update CSPI status when corresponding cStor pool-manager terminated
  build/pool-manager/Dockerfile
  build/pool-manager/entrypoint.sh
  pkg/controllers/cspi-controller/handler.go
  pkg/controllers/cspi-controller/handler_test.go
  pkg/controllers/cspi-controller/runner.go
Labels: area: pool-manager

#145 docs(cstorvolume): add cStor volume resource organisation document.
  README.md
  docs/developer-guide/cstor-pool.md
  docs/developer-guide/cstor-volume.md
Labels: documentation, needs-review

#147 chore(validations): add check for BD tag presence
  go.mod
  go.sum
  pkg/webhook/cspc.go
  vendor/github.com/openebs/api/pkg/apis/types/types.go
  vendor/modules.txt
Labels: admission-webhook

#148 feat(tests): add integration test cases for changing the policies on CVC dynamically
  tests/cstorvolume/provisioing/provisioning_test.go
  tests/cstorvolume/provisioing/provisioning_utils.go
  tests/pkg/cstorvolumeconfig/cvcspecbuilder/specbuilder.go
  tests/pkg/k8sclient/cspc_util.go
  tests/pkg/k8sclient/cv_util.go
  tests/pkg/k8sclient/cvc_util.go
  tests/pkg/k8sclient/pvc_util.go
Labels: needs-review

#151 feat(tests): add integration tests for scaleup and scaledown of CStorVolume
  tests/cstorvolume/provisioing/provisioning_test.go
  tests/cstorvolume/provisioing/provisioning_utils.go
  tests/pkg/cstorvolumeconfig/cvcspecbuilder/specbuilder.go
  tests/pkg/k8sclient/cspc_util.go
  tests/pkg/k8sclient/cv_util.go
  tests/pkg/k8sclient/cvc_util.go
  tests/pkg/k8sclient/cvr_util.go
  tests/pkg/k8sclient/pvc_util.go
Labels: needs-review

#154 chore(docs): update README and quick.md files
  README.md
  docs/quick.md
  docs/tutorial/cspc/tuning/tune.md
  docs/tutorial/intro.md
Labels: documentation

#150 test(cspc): add cspc tunables test
  tests/cspc/provisioning/provisioning_test.go
  tests/pkg/cspc/cspcspecbuilder/specbuilder.go
  tests/pkg/k8sclient/cspc_util.go
Labels: needs-review

#169 Bump golang version to 1.14.7
  .github/workflows/go.yml
  .travis.yml
Labels: needs-review

#170 chore(ci): add license check in ci
  .github/workflows/go.yml
  Makefile
  pkg/controllers/cspc-controller/util/cspc_util_test.go
  pkg/controllers/cstorvolumeconfig/volume_operations_test.go
  pkg/snapshot/snapshottest/snapshot.go
  pkg/version/util.go
  pkg/volume-rpc/targetserver/config.go
  pkg/zcmd/zfs/stats/stats.go
  tests/cstorvolume/provisioing/provisioning_utils.go
Labels: needs-review
