Repository openebs/cstor-operators, pull requests merged in 2020-09, with the labels that each got.

#172 feat(cspc): add capability to specify allowed BD tags on CSPC
  go.mod
  go.sum
  pkg/controllers/cspc-controller/util/cspc_util_test.go
  pkg/controllers/cstorvolumeconfig/volume_operations_test.go
  pkg/cspc/algorithm/select_node.go
  pkg/cspc/algorithm/select_node_test.go
  pkg/snapshot/snapshottest/snapshot.go
  pkg/version/util.go
  pkg/volume-rpc/targetserver/config.go
  pkg/webhook/cspc.go
  pkg/webhook/cspc_operations.go
  pkg/webhook/cspc_operations_test.go
  pkg/zcmd/zfs/stats/stats.go
  tests/cstorvolume/provisioing/provisioning_utils.go
  vendor/github.com/openebs/api/pkg/apis/types/types.go
  vendor/modules.txt
Labels: admission-webhook, area: cspc-operator, needs-review, pr/release-note

#179 chore(docs): add csi cstor volume metrics exposed by prometheus
  deploy/csi-operator.yaml
  docs/tutorial/intro.md
  docs/tutorial/volumes/prometheus-monitoring.md
Labels: documentation

#181 docs(bd-tag): add tutorial for using BD tag feature.
  docs/tutorial/cspc/allow-tagged-bds/allowed-bds.md
  docs/tutorial/intro.md
Labels: documentation, needs-review

#183 feat(backup, restore): promote backup and restore controller to use v1 apis
  cmd/pool-manager/main.go
  go.mod
  go.sum
  pkg/controllers/backup-controller/controller.go
  pkg/controllers/backup-controller/handler.go
  pkg/controllers/restore-controller/handler.go
  pkg/controllers/restore-controller/new_restore_controller.go
  pkg/volumereplica/volumereplica.go
  vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorbackup.go
  vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorbackuprestorebuilder.go
  vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorcompletebackup.go
  vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorrestore.go
  vendor/github.com/openebs/api/pkg/apis/cstor/v1/register.go
  vendor/github.com/openebs/api/pkg/apis/cstor/v1/zz_generated.deepcopy.go
  vendor/github.com/openebs/api/pkg/apis/openebs.io/v1alpha1/migrationtask.go
  vendor/github.com/openebs/api/pkg/apis/openebs.io/v1alpha1/register.go
  vendor/github.com/openebs/api/pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/cstor_client.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/cstorbackup.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/cstorcompletedbackup.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/cstorrestore.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/fake/fake_cstor_client.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/fake/fake_cstorbackup.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/fake/fake_cstorcompletedbackup.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/fake/fake_cstorrestore.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/cstor/v1/generated_expansion.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_migrationtask.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_openebs.io_client.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/openebs.io/v1alpha1/generated_expansion.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/openebs.io/v1alpha1/migrationtask.go
  vendor/github.com/openebs/api/pkg/client/clientset/versioned/typed/openebs.io/v1alpha1/openebs.io_client.go
  vendor/github.com/openebs/api/pkg/client/informers/externalversions/cstor/v1/cstorbackup.go
  vendor/github.com/openebs/api/pkg/client/informers/externalversions/cstor/v1/cstorcompletedbackup.go
  vendor/github.com/openebs/api/pkg/client/informers/externalversions/cstor/v1/cstorrestore.go
  vendor/github.com/openebs/api/pkg/client/informers/externalversions/cstor/v1/interface.go
  vendor/github.com/openebs/api/pkg/client/informers/externalversions/generic.go
  vendor/github.com/openebs/api/pkg/client/informers/externalversions/openebs.io/v1alpha1/interface.go
  vendor/github.com/openebs/api/pkg/client/informers/externalversions/openebs.io/v1alpha1/migrationtask.go
  vendor/github.com/openebs/api/pkg/client/listers/cstor/v1/cstorbackup.go
  vendor/github.com/openebs/api/pkg/client/listers/cstor/v1/cstorcompletedbackup.go
  vendor/github.com/openebs/api/pkg/client/listers/cstor/v1/cstorrestore.go
  vendor/github.com/openebs/api/pkg/client/listers/cstor/v1/expansion_generated.go
  vendor/github.com/openebs/api/pkg/client/listers/openebs.io/v1alpha1/expansion_generated.go
  vendor/github.com/openebs/api/pkg/client/listers/openebs.io/v1alpha1/migrationtask.go
  vendor/github.com/openebs/api/pkg/internalapis/apis/cstor/cstorbackup.go
  vendor/github.com/openebs/api/pkg/internalapis/apis/cstor/cstorcompletebackup.go
  vendor/github.com/openebs/api/pkg/internalapis/apis/cstor/cstorrestore.go
  vendor/github.com/openebs/api/pkg/internalapis/apis/cstor/register.go
  vendor/github.com/openebs/api/pkg/internalapis/apis/cstor/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs-review
