Repository openebs/cstor-operators, pull requests merged in 2021-05, with the labels that each got.

#320 Added Gitpod config
  .gitpod.yml
  CONTRIBUTING.md
  README.md
Labels: event/kubecon-eu21-bugbash

#308 (bugsbash) fix return statements
  pkg/controllers/backup-controller/controller.go
  pkg/controllers/backup-controller/handler.go
Labels: event/kubecon-eu21-bugbash

#317 code changes in a better format
  pkg/controllers/cspc-controller/status.go
  pkg/controllers/replica-controller/handler.go
  pkg/controllers/restore-controller/handler.go
Labels: event/kubecon-eu21-bugbash

#322 Changed md5 to sha256 algorithm
  pkg/controllers/cstorvolumeconfig/volume_operations.go
  pkg/util/hash/hash.go
Labels: event/kubecon-eu21-bugbash, pr/hold-merge

#289 Remove unused struct CmdSnaphotOptions
  cmd/volume-manager/app/commands.go
Labels: event/kubecon-eu21-bugbash

#313 Remove usage of fmt.sprintf
  pkg/zcmd/zpool/attach/builder.go
  pkg/zcmd/zpool/destroy/builder.go
  pkg/zcmd/zpool/export/builder.go
Labels: event/kubecon-eu21-bugbash, pr/hold-review

#314 fixed all opt.semgrep.err-nil-check issues
  pkg/controllers/cspc-controller/scale.go
  pkg/controllers/cspc-controller/sync.go
  pkg/controllers/cspi-controller/handler_test.go
  pkg/controllers/cstorvolumeconfig/controller.go
  pkg/pool/operations/disk_operation.go
  pkg/server/cstorvolumeconfig/restore_endpoint.go
  pkg/webhook/cspc_operations.go
  pkg/webhook/cvc.go
  pkg/zcmd/zfs/listsnap/builder.go
Labels: event/kubecon-eu21-bugbash, pr/hold-review

#318 Remove usage of fmt.sprintf
  pkg/zcmd/zpool/labelclear/builder.go
Labels: event/kubecon-eu21-bugbash, pr/hold-review

#319 Remove usage of fmt.sprintf
  pkg/zcmd/zpool/offline/builder.go
  pkg/zcmd/zpool/online/builder.go
Labels: event/kubecon-eu21-bugbash

#305 Move usr/bin declaration to top of file
  ci/sanity/install.sh
  ci/sanity/sanity.sh
Labels: event/kubecon-eu21-bugbash, pr/hold-merge

#310 Remove usage of fmt.string in cmd/volume-manager/app/commands.go
  cmd/volume-manager/app/commands.go
Labels: event/kubecon-eu21-bugbash
